name: example_model
train_command: 'Rscript train.R {train_data} {model}'
predict_command: 'Rscript predict.R {model} {future_data} {out_file}'
adapters: {'Y': 'disease_cases',
           'E': 'population',
           'T1': 'week',
           'T2': 'year',
           'S1': 'location',
           'rainsum': 'rainfall',
           'meantemperature': 'mean_temperature'}
dockername: ivargr/r_inla
